# Site settings
title: Microdust 微尘
header-img: img/seagulls.jpg
tagline: "「在遙遠的地方 一切虔誠終必相遇」"  
description: "明朝即長路 惜取此時心"  
baseurl: "http://azeril.me"
url: "http://azeril.me"  

# About/contact
author:
  name:              Azeril
  email:             azeril@live.cn

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

twitter_username: Azeril_Lapland  
github_username:  Azeril  
facebook_username:  Azeril_Lapland  
weibo_username: Azeril  
zhihu_username: Azeril  


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Azeril"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : lapland
  disqus :
      short_name : Azeril