# Site settings
title: Microdust 微塵
header-img: img/home-bg.jpg
email: azeril@live.cn 
description: "明朝即長路 惜取此時心"
baseurl: ""
url: "http://azeril.me"
twitter_username: Azeril_Lapland
github_username:  Azeril 
facebook_username:  Azeril_Lapland  
weibo_username: Azeril
zhihu_username: Azeril


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
